LOAD DATA LOCAL INFILE 'grad_students.csv' INTO TABLE mentors
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'prerequisite_courses.csv' INTO TABLE prerequisite_courses
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 ROWS;

